[package]
name = "openvm-te-guest"
description = "OpenVM guest library for elliptic curve cryptography with twisted Edwards curves"
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
openvm = { workspace = true }
serde = { workspace = true }
strum_macros.workspace = true
openvm-custom-insn = { workspace = true }
openvm-rv32im-guest = { workspace = true }
openvm-algebra-guest = { workspace = true }
openvm-algebra-moduli-macros = { workspace = true }
openvm-ecc-guest = { workspace = true }
openvm-ecc-te-macros = { workspace = true }
once_cell = { workspace = true, features = ["race", "alloc"] }
num-bigint = { workspace = true }
hex-literal = { workspace = true }

# Used for `halo2curves` feature
halo2curves-axiom = { workspace = true, optional = true }

[target.'cfg(not(target_os = "zkvm"))'.dependencies]
lazy_static = { workspace = true }

[features]
default = []
ed25519 = []
halo2curves = ["dep:halo2curves-axiom", "openvm-algebra-guest/halo2curves"]
std = ["alloc"]
alloc = []

[package.metadata.cargo-shear]
ignored = [
    "openvm",
    "openvm-custom-insn",
    "openvm-rv32im-guest",
    "halo2curves-axiom",
]
