[app_vm_config.rv32i]
[app_vm_config.rv32m]
[app_vm_config.io]
[app_vm_config.modular]
supported_moduli = ["115792089237316195423570985008687907853269984665640564039457584007908834671663", "115792089237316195423570985008687907852837564279074904382605163141518161494337", "57896044618658097711785492504343953926634992332820282019728792003956564819949"]

[[app_vm_config.ecc.supported_curves]]
struct_name = "Secp256k1Point"
modulus = "115792089237316195423570985008687907853269984665640564039457584007908834671663"
scalar = "115792089237316195423570985008687907852837564279074904382605163141518161494337"
a = "0"
b = "7"

[[app_vm_config.edwards.supported_curves]]
struct_name = "Ed25519Point"
modulus = "57896044618658097711785492504343953926634992332820282019728792003956564819949"
scalar = "7237005577332262213973186563042994240857116359379907606001950938285454250989"
a = "57896044618658097711785492504343953926634992332820282019728792003956564819948"
d = "37095705934669439343138083508754565189542113879843219016388785533085940283555"
