global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'openvm-benchmark'
    static_configs:
      - targets: ['host.docker.internal:9091']
    honor_labels: true
    scrape_interval: 5s
    scrape_timeout: 5s
