[package]
name = "openvm-keccakf-transpiler"
description = "OpenVM transpiler extension for keccakf"
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
openvm-stark-backend = { workspace = true }
openvm-instructions = { workspace = true }
openvm-transpiler = { workspace = true }
rrs-lib = { workspace = true }
openvm-keccakf-guest = { workspace = true }
openvm-instructions-derive = { workspace = true }
strum = { workspace = true }
