[package]
name = "openvm-circuit-primitives-derive"
description = "Procedural macros for writing circuits as AIRs."
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full", "parsing", "extra-traits"] }
quote = "1.0"
itertools = { workspace = true, default-features = true }
proc-macro2 = "1.0"

[dev-dependencies]
ndarray.workspace = true

[package.metadata.cargo-shear]
ignored = ["ndarray"]
