[package]
name = "openvm-rv64im-transpiler"
description = "OpenVM transpiler extension for RISC-V 64-bit IM instruction set"
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
openvm-stark-backend = { workspace = true }
openvm-instructions = { workspace = true }
openvm-transpiler = { workspace = true }
openvm-decoder = { workspace = true }
tracing = { workspace = true }
openvm-rv64im-guest = { workspace = true }
openvm-instructions-derive = { workspace = true }
strum = { workspace = true }
serde = { workspace = true, features = ["derive"] }
