[package]
name = "asm_bridge_metered"
version.workspace = true 
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[package.metadata.cargo-shear]
ignored = ["cc"]

[lib]
crate-type = ["cdylib"]

[dependencies]
cc = "1.0"
openvm-circuit = { workspace = true, default-features = false }
openvm-stark-sdk = { workspace = true, default-features = false }
openvm-instructions = { workspace = true, default-features = false }
